#pragma once

#include <cstdint>
#include <winuser.h>

namespace Input {
  enum class Key : std::uint16_t;
}

enum class Input::Key : std::uint16_t {
  Unknown        = 0,
  ShiftLeft      = 16,  // VK_LSHIFT,
  LShift         = 16,  // VK_LSHIFT,
  ShiftRight     = VK_RSHIFT,
  RShift         = VK_RSHIFT,
  ControlLeft    = VK_LCONTROL,
  LControl       = VK_LCONTROL,
  ControlRight   = VK_RCONTROL,
  RControl       = VK_RCONTROL,
  WinLeft        = VK_LWIN,
  LWin           = VK_LWIN,
  WinRight       = VK_RWIN,
  RWin           = VK_RWIN,
  Menu           = VK_MENU,
  F1             = VK_F1,
  F2             = VK_F2,
  F3             = VK_F3,
  F4             = VK_F4,
  F5             = VK_F5,
  F6             = VK_F6,
  F7             = VK_F7,
  F8             = VK_F8,
  F9             = VK_F9,
  F10            = VK_F10,
  F11            = VK_F11,
  F12            = VK_F12,
  F13            = VK_F13,
  F14            = VK_F14,
  F15            = VK_F15,
  F16            = VK_F16,
  F17            = VK_F17,
  F18            = VK_F18,
  F19            = VK_F19,
  F20            = VK_F20,
  F21            = VK_F21,
  F22            = VK_F22,
  F23            = VK_F23,
  F24            = VK_F24,
  Up             = VK_UP,
  Down           = VK_DOWN,
  Left           = VK_LEFT,
  Right          = VK_RIGHT,
  Enter          = VK_RETURN,
  Escape         = VK_ESCAPE,
  Space          = VK_SPACE,
  Tab            = VK_TAB,
  BackSpace      = VK_BACK,
  Back           = VK_BACK,
  Insert         = VK_INSERT,
  Delete         = VK_DELETE,
  Home           = VK_HOME,
  End            = VK_END,
  ScrollLock     = VK_SCROLL,
  PrintScreen    = VK_PRINT,
  Pause          = VK_PAUSE,
  NumLock        = VK_NUMLOCK,
  Clear          = VK_CLEAR,
  Sleep          = VK_SLEEP,
  Keypad0        = VK_NUMPAD0,
  Keypad1        = VK_NUMPAD1,
  Keypad2        = VK_NUMPAD2,
  Keypad3        = VK_NUMPAD3,
  Keypad4        = VK_NUMPAD4,
  Keypad5        = VK_NUMPAD5,
  Keypad6        = VK_NUMPAD6,
  Keypad7        = VK_NUMPAD7,
  Keypad8        = VK_NUMPAD8,
  Keypad9        = VK_NUMPAD9,
  KeypadDivide   = VK_DIVIDE,
  KeypadMultiply = VK_MULTIPLY,
  KeypadSubtract = VK_SUBTRACT,
  KeypadMinus    = VK_SUBTRACT,
  KeypadAdd      = VK_ADD,
  KeypadPlus     = VK_ADD,
  KeypadDecimal  = VK_DECIMAL,
  KeypadEnter    = VK_RETURN,
  A              = 'A',
  B              = 'B',
  C              = 'C',
  D              = 'D',
  E              = 'E',
  F              = 'F',
  G              = 'G',
  H              = 'H',
  I              = 'I',
  J              = 'J',
  K              = 'K',
  L              = 'L',
  M              = 'M',
  N              = 'N',
  O              = 'O',
  P              = 'P',
  Q              = 'Q',
  R              = 'R',
  S              = 'S',
  T              = 'T',
  U              = 'U',
  V              = 'V',
  W              = 'W',
  X              = 'X',
  Y              = 'Y',
  Z              = 'Z',
  Number0        = VK_NUMPAD0,
  Number1        = VK_NUMPAD1,
  Number2        = VK_NUMPAD2,
  Number3        = VK_NUMPAD3,
  Number4        = VK_NUMPAD4,
  Number5        = VK_NUMPAD5,
  Number6        = VK_NUMPAD6,
  Number7        = VK_NUMPAD7,
  Number8        = VK_NUMPAD8,
  Number9        = VK_NUMPAD9,
  Minus          = VK_SUBTRACT,
  Plus           = VK_ADD,
  LastKey,
};
